import React from 'react';
import Accordion from 'react-bootstrap/Accordion';
import "../styles/help.css";
import HelpNav from '../components/helpNav';

function HelpPage() {
  return (
    <div className='helpEverything'> 
        <HelpNav />
        <div className='helpPageEverything'>
        <div className='helpPageBox'>
            <div className='helpPage'>
            <h1 className='helpTitle'>Help Page</h1>
            <h3 className='helpSubtitle'>Welcome to the Salus Help Page!
            Embark on a seamless journey with Salus, your trusted companion in personal finance management. 
            This help page is designed to offer you comprehensive guidance on effectively utilizing our web application.
             Here, you will find detailed instructions on managing your expenses, setting up budgets, 
             and understanding the insightful financial reports generated by Salus. 
             We are here to ensure your experience with Salus is both rewarding and effortless.
            </h3>
            <Accordion className='accordion'>
            <Accordion.Item eventKey="0">
                <Accordion.Header>Introduction</Accordion.Header>
                <Accordion.Body>
                    <p>
                    <strong>Salus</strong> is a dynamic web-based application crafted to streamline your personal finance management. Our platform is dedicated to empowering users like you with effective tools for overseeing and optimizing your financial health. Here’s what Salus offers:
                    </p>

                    <ul>
                    <li>
                        <strong>Expense Tracking:</strong> Keep a vigilant eye on your spending. Salus simplifies logging and categorizing your expenses, making it easier to understand where your money goes.
                    </li>
                    <li>
                        <strong>Budget and Saving Goals:</strong> Set realistic budgets and saving targets with ease. Our intuitive interface helps you define and adhere to your financial goals, fostering responsible spending and effective saving habits.
                    </li>
                    <li>
                        <strong>Financial Reporting:</strong> Gain insightful perspectives on your financial status through our comprehensive reports. These detailed analyses provide clarity on your financial journey, aiding in informed decision-making.
                    </li>
                    <li>
                        <strong>Secure Database:</strong> Rest assured, your financial data is safe with us. Salus securely stores all your transactions, budgets, and profiles in a meticulously organized database, ensuring both security and ease of access.
                    </li>
                    </ul>

                    <p>
                    Our commitment is to offer you a user-friendly and efficient platform that supports your journey towards financial responsibility and savvy. Whether you are planning your monthly budget, tracking expenses, or setting long-term financial goals, Salus is here to guide you every step of the way.
                    </p>
                </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="1">
                <Accordion.Header>How do I create a new account?</Accordion.Header>
                <Accordion.Body>
                    To create a new account, click on the "Sign Up" button and fill out the required information.
                </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="2">
                <Accordion.Header>How do I reset my password?</Accordion.Header>
                <Accordion.Body>
                    To reset your password, click on the pencil icon on your user page. From here you will be able to change your password.
                </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="3">
                <Accordion.Header>How do I contact customer support?</Accordion.Header>
                <Accordion.Body>
                    To contact customer support, please email salus@support.com.
                </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="4">
                <Accordion.Header>How do I add my transactions?</Accordion.Header>
                <Accordion.Body>
                    <p>
                    Adding transactions <strong>individually</strong>:
                    </p>
                    <ul>
                        <li>
                            Go to the <strong>Transactions</strong> page
                        </li>
                        <li>
                            At the top right of the page, you will see two buttons that say <strong>Add expense</strong> and <strong>Add income</strong>, click on them depending on what you would like to add.
                        </li>
                        <li>
                            Fill out <strong>each</strong> field in the pop-up
                        </li>
                        <li>
                            Once you are certain each field has been filled out correctly, click on the <strong>Add expense/income</strong> button in the bottom of the pop-up to finalize your changes!
                        </li>
                    </ul>
                    <p>
                    Adding multiple transactions at once with <strong>CSV Importing</strong>:
                    </p>
                    <ul>
                        <li>
                            Go to the <strong>Transactions</strong> page
                        </li>
                        <li>
                            At the top left of the page, you will see a button that says <strong>CSV Templates</strong>, click on it to download a zip file containing two CSV files, one that has the headers needed for uploading expenses and the other with the headers needed for uploading your income. <strong>Note</strong>: If you already downloaded your expenses and/or income in a CSV file, just make sure you have the same headers as the templates provided.
                        </li>
                        <li>
                            For each expense or income, <strong>all</strong> of the columns <strong>except</strong> for the first ones, which should say either <strong>expenses</strong> or <strong>income</strong>, must be filled out with their proper information.
                        </li>
                        <li>
                            Once you have your CSV file(s) filled out with all of the transactions you would like to import, in the <strong>Transactions</strong> page, under the <strong>CSV Templates</strong> button you clicked, click on the <strong>Choose File</strong> to then select your CSV file. You can only upload one file at a time, so if you have expenses and income you would like to upload, you must select one first, then select the other after uploading the previous one.
                        </li>
                        <li>
                            After selecting your file, which you can confirm if you did or didn't by ensuring that the text next to the <strong>Choose File</strong> button doesn't say <strong>No file chosen</strong>, you can then click on the <strong>Upload</strong> button below to upload your transactions.
                        </li>
                    </ul>
                </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="5">
                <Accordion.Header>How do I add a savings goal?</Accordion.Header>
                <Accordion.Body>
                    <ul>
                        <li>
                            Go to the <strong>Savings</strong> page
                        </li>
                        <li>
                            Click the <strong>plus sign</strong> next to where it says "Your Savings"
                        </li>
                        <li>
                            Fill out the appropriate information for your goal such as the <strong>name of the goal</strong>, <strong> the amount you want to save for </strong>, and <strong>how much you have already contributed </strong>. If you do not specify a contributed amount, this value will default to 0.
                        </li>
                        <li>
                            Press <strong>submit</strong> and close the "Add a New Goal" window. If you do not see your new goal appear, refresh the page.
                        </li>
                    </ul>
                     See "How do I manage my savings?" for more information on editing goals and accessing the history of your savings contributions.
                </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="6">
                <Accordion.Header>How do I manage my savings?</Accordion.Header>
                <Accordion.Body>
                    <p>
                    <strong>Editing Goals and Making Contributions</strong>:
                    </p>
                    <ul>
                        <li>
                            Go to the <strong>Savings</strong> page
                        </li>
                        <li>
                            Click the <strong>pencil icon</strong> on any of your goals.
                        </li>
                        <li>
                            Change the appropriate information for your goal such as the <strong>name of the goal</strong>, <strong> the amount you want to save for </strong>, or how much you want to <strong>add to or subtract from the contributed amount</strong>.
                        </li>
                        <li>
                            Press <strong>submit</strong> and close the "Edit Goal" window. If you do not see your changes appear, refresh the page.
                        </li>
                    </ul>
                    <p>
                    <strong>Deleting Goals</strong>:
                    </p>
                     <ul>
                        <li>
                            Go to the <strong>Savings</strong> page
                        </li>
                        <li>
                            Click the <strong>"X"</strong> on any of your goals.
                        </li>
                        <li>
                           Press <strong>"Delete"</strong> in the pop up to delete. Otherwise, press  <strong>"Cancel"</strong> to cancel this action.
                        </li>
                        <li>
                            If you do not see your goal delete, refresh the page.
                        </li>
                    </ul>
                    <p>
                    <strong>See History of Savings Transactions</strong>:
                    </p>
                     <ul>
                        <li>
                            Go to the <strong>Savings</strong> page
                        </li>
                        <li>
                            <strong>Click on any of your goals. </strong> You will see a pop up with a table of your savings transactions.
                        </li>
                        <li>
                           Specify a <strong>start date</strong> or an <strong>end date </strong> to see a more specific range of transaction dates.
                        </li>
                        <li>
                            Press the <strong>up or down arrows</strong> if you want to sort by ascending or descending, respectively.
                        </li>
                        <li>
                            Close the pop up when you are done by pressing X or clicking outside of the pop up.
                        </li>
                    </ul>
                     
                </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="7">
                <Accordion.Header>How do I add a budget?</Accordion.Header>
                <Accordion.Body>
                    <ul>
                        <li>
                            Go to the <strong>Budget</strong> page.
                        </li>
                        <li>
                            Click the <strong>plus sign</strong> across the section where it says "Your Budgets".
                        </li>
                        <li>
                            Fill out the appropriate information for your new budget such as the name of the budget, the limit for the budget, and the month and year for the budget.
                        </li>
                        <li>
                            Once every input field is filled, click on the <strong>Add Budget</strong> button at the bottom of the window to finalize your new budget's information.
                        </li>
                    </ul>
                    See "How do I add my transactions?" for more information on filling your budgets.
                </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="8">
                <Accordion.Header>How do I manage my budgets?</Accordion.Header>
                <Accordion.Body>
                <p>
                    <strong>Editing Budgets</strong>:
                </p>
                <ul>
                    <li>
                        Go to the <strong>Budget</strong> page.
                    </li>
                    <li>
                        Click the <strong>pencil icon</strong> on any of your budgets.
                    </li>
                    <li>
                        In the window that appears, you are able to change the <strong>name</strong> and the <strong>limit</strong> for your budget.
                    </li>
                    <li>
                        Once you are satisfied with the changes, make sure to finalize them by pressing the <strong>Update Budget</strong> button and close the "Edit Budget" window.
                    </li>
                </ul>
                <p>
                    <strong>Deleting Budgets</strong>
                </p>
                <ul>
                    <li>
                        Go to the <strong>Budget</strong> page.
                    </li>
                    <li>
                        Click the <strong>"X"</strong> on any of your budgets.
                    </li>
                    <li>
                        Press <strong>"Delete"</strong> in the pop up window to delete. Otherwise, press  <strong>"Cancel"</strong> to cancel this action.
                    </li>
                </ul>
                </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="9">
                <Accordion.Header>How do I manage the total budget?</Accordion.Header>
                <Accordion.Body>
                    The <strong>Total Budget</strong> where you'll be able to see how much money you have total in the form of a monthly budget and it shows how much is left. Every change, whether it is adding a budget, deleting a budget, or editing a budget, will cause the total budget to change to reflect that. See previous help sections if need be.
                </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="10">
                <Accordion.Header>How do I find all my budgets?</Accordion.Header>
                <Accordion.Body>
                    The defualt view of your budgets are those created for the <strong>current month and year</strong>. Use the <strong>Prev</strong> button and the <strong>Next</strong> button to switch to different months to view other budgets assigned to their respective month and year.
                </Accordion.Body>
                </Accordion.Item>
            </Accordion>
            </div>
        </div>
        </div>
    </div>
  );
};

export default HelpPage;