import React from 'react';
import Accordion from 'react-bootstrap/Accordion';
import "../styles/help.css";
import HelpNav from '../components/helpNav';

function HelpPage() {
  return (
    <div className='helpEverything'> 
        <HelpNav />
        <div className='helpPageEverything'>
        <div className='helpPageBox'>
            <div className='helpPage'>
            <h1 className='helpTitle'>Help Page</h1>
            <h3 className='helpSubtitle'>Welcome to the Salus Help Page!
            Embark on a seamless journey with Salus, your trusted companion in personal finance management. 
            This help page is designed to offer you comprehensive guidance on effectively utilizing our web application.
             Here, you will find detailed instructions on managing your expenses, setting up budgets, 
             and understanding the insightful financial reports generated by Salus. 
             We are here to ensure your experience with Salus is both rewarding and effortless.
            </h3>
            <Accordion className='accordion'>
            <Accordion.Item eventKey="0">
                <Accordion.Header>Introduction</Accordion.Header>
                <Accordion.Body>
                    <p>
                    <strong>Salus</strong> is a dynamic web-based application crafted to streamline your personal finance management. Our platform is dedicated to empowering users like you with effective tools for overseeing and optimizing your financial health. Here’s what Salus offers:
                    </p>

                    <ul>
                    <li>
                        <strong>Expense Tracking:</strong> Keep a vigilant eye on your spending. Salus simplifies logging and categorizing your expenses, making it easier to understand where your money goes.
                    </li>
                    <li>
                        <strong>Budget and Saving Goals:</strong> Set realistic budgets and saving targets with ease. Our intuitive interface helps you define and adhere to your financial goals, fostering responsible spending and effective saving habits.
                    </li>
                    <li>
                        <strong>Financial Reporting:</strong> Gain insightful perspectives on your financial status through our comprehensive reports. These detailed analyses provide clarity on your financial journey, aiding in informed decision-making.
                    </li>
                    <li>
                        <strong>Secure Database:</strong> Rest assured, your financial data is safe with us. Salus securely stores all your transactions, budgets, and profiles in a meticulously organized database, ensuring both security and ease of access.
                    </li>
                    </ul>

                    <p>
                    Our commitment is to offer you a user-friendly and efficient platform that supports your journey towards financial responsibility and savvy. Whether you are planning your monthly budget, tracking expenses, or setting long-term financial goals, Salus is here to guide you every step of the way.
                    </p>
                </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="1">
                <Accordion.Header>How do I create a new account?</Accordion.Header>
                <Accordion.Body>
                    To create a new account, click on the "Sign Up" button and fill out the required information.
                </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="2">
                <Accordion.Header>How do I reset my password?</Accordion.Header>
                <Accordion.Body>
                    To reset your password, click on the "Forgot Password" link and follow the instructions sent to your email.
                </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="3">
                <Accordion.Header>How do I contact customer support?</Accordion.Header>
                <Accordion.Body>
                    To contact customer support, please email salus@support.com.
                </Accordion.Body>
                </Accordion.Item>
            </Accordion>
            </div>
        </div>
        </div>
    </div>
  );
};

export default HelpPage;